[package]
name = "ray-tracing"
version = "0.1.0"
edition = "2021"


[alias]
rr = "run --release"
br = "build --release"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
dyn-clone = "1.0.17"
rand = "0.8.5"
