[camera]
file_path = 'cornell-box.ppm'
aspect_ratio = 1.0
image_width = 400
samples_per_pixel = 100
max_depth = 50
vfov = 40.0
defocus_angle = 0.0
focus_dist = 10.0
background = [0.0, 0.0, 0.0]
look_from = [278.0, 278.0, -800.0]
look_at = [278.0, 278.0, 0.0]
vup = [0.0, 1.0, 0.0]

[scene]
objects = [
  { type = "quad", corner = [ 555.0, 0.0, 0.0, ], u = [ 0.0, 555.0, 0.0, ], v = [ 0.0, 0.0, 555.0, ], material = "green" },
  { type = "quad", corner = [0.0, 0.0, 0.0], u = [0.0, 555.0, 0.0], v = [0.0, 0.0, 555.0], material = "red" },
  { type = "quad", corner = [0.0, 0.0, 0.0], u = [555.0, 0.0, 0.0], v = [0.0, 0.0, 555.0], material = "white" },
  { type = "quad", corner = [555.0, 555.0, 555.0], u = [-555.0, 0.0, 0.0], v = [0.0, 0.0, -555.0], material = "white" },
  { type = "quad", corner = [0.0, 0.0, 555.0], u = [555.0, 0.0, 0.0], v = [0.0, 555.0, 0.0], material = "white" }
]
lights = []

[scene.materials]
empty_mat = { type = "none" }
red = { type = "lambertian", color = [0.65, 0.05, 0.05] }
white = { type = "lambertian", color = [0.73, 0.73, 0.73] }
green = { type = "lambertian", color = [0.12, 0.45, 0.15] }
light = { type = "diffuse_light", color = [7.0, 7.0, 7.0] }
